"""initial schema

Revision ID: 3baa3d75b71b
Revises: 9c8091060be4
Create Date: 2025-11-17 00:11:23.048233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3baa3d75b71b'
down_revision: Union[str, Sequence[str], None] = '9c8091060be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sections', sa.Column('professor_name', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('units', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('description', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'units')
    op.drop_column('class_sections', 'professor_name')
    # ### end Alembic commands ###
